# Generated by Django 4.1.3 on 2022-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='First Name')),
                ('Last_Name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Password', models.CharField(max_length=50, verbose_name='Password')),
                ('Re_Password', models.CharField(max_length=50, verbose_name='Re_Password')),
            ],
        ),
    ]
