# Generated by Django 4.1.3 on 2023-02-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First_Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last_Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Field')),
            ],
        ),
    ]
