# Generated by Django 4.1.3 on 2022-12-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='email'),
        ),
    ]
