# Generated by Django 4.1.3 on 2023-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_venue_venue_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('-name',), 'verbose_name': 'Postion', 'verbose_name_plural': 'Test'},
        ),
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
